### ISSUE TITLE
some flaky chars in NayvyImportsFzF

### ISSUE THREAD

**Issue by Shane-XB-Qian** [relastle/vim-nayvy#16]
![image](https://github.com/relastle/vim-nayvy/assets/13550529/b1ccfe85-c6b8-47d6-b298-bbcf40dd8483)

1. the color escape chars looks dup or wrong.
2. the init `I` do not understand where is it from.

**Comment by Shane-XB-Qian** [comment]
there is flaky `I` when/in NayvyTestGenerateFZF too.

**Comment by relastle** [comment]
@Shane-XB-Qian 

Could you please check whether or not followings fix the problem

- Rxecute in shell `echo $FZF_DEFAULT_OPTS `
- If `--ansi` option is not there, add `--ansi` in $FZF_DEFAULT_OPTS
- Run `NayvyImportsFzF` again

**Comment by Shane-XB-Qian** [comment]
> * If `--ansi` option is not there, add `--ansi` in $FZF_DEFAULT_OPTS

ok, thanks, yes, so looks this only recogonize ansi palettes

**Comment by Shane-XB-Qian** [comment]
> 2\. the init `I` do not understand where is it from.

how about this one? why there is an init `I` char?

**Comment by relastle** [comment]
> > * If `--ansi` option is not there, add `--ansi` in $FZF_DEFAULT_OPTS
> 
> ok, thanks, yes, so looks this only recogonize ansi palettes

umm..., I don't have any idea why.
nayvy just prints ansi palettes escape sequences to the standard output and pass thme to fzf.

If colored output is not necessary, just tweks the flag (see following link) will fix the problem.

https://github.com/relastle/vim-nayvy/blob/d5882540779149e499c00fa876bb76170b0f98ec/python3/nayvy_vim_if/importing.py#L199

**Comment by relastle** [comment]
> > 2. the init `I` do not understand where is it from.
> 
> how about this one? why there is an init `I` char?

I cannot reproduce this problem also, and have no idea about it 😢

**Comment by Shane-XB-Qian** [comment]
![image](https://github.com/relastle/vim-nayvy/assets/13550529/fe198fc1-721b-4297-ba93-011673ee29b8)

something like here? it had a strange `I` ahead.

**Comment by relastle** [comment]
@Shane-XB-Qian 

Unfortunately no, this script is just a configuration file for automatically producing the [GIF](https://github.com/relastle/vim-nayvy#nayvyimportfzf).
And, insertion of `I` is not repdoducable for me, so this is some environment-specific problem.

**Comment by Shane-XB-Qian** [comment]
> Unfortunately no, this script is just a configuration file for automatically producing the [GIF](https://github.com/relastle/vim-nayvy#nayvyimportfzf).

i was just a guess: maybe similar some kinds of such keystrokes somewhere, it should be a input char but not sure where generated it.

**Comment by Shane-XB-Qian** [comment]
let me do another guess: seems this is a char from focusgain esc code, if/seems yes, do you know where/if fzf_opts had such option to overcome it?

**Comment by Shane-XB-Qian** [comment]
anyway, it is a problem when/if integ with fzf.
let it be..
